title: Welcome to Justine's Corner!
author: Justine
email: justineyongjzxy@gmail.com
description:  Hai, it's Justine! This is my Github website based on the Github course. 
# social links
twitter_username: no twitter account # DO NOT include the @ character, or else the build will fail!
github_username:  Squagalings # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
